export const topGainers = [
  {
    name: "Sarah J.",
    gain: 19.23,
    emoji: "👩‍💼",
  },
  {
    name: "Mike R.",
    gain: 15.87,
    emoji: "👨‍💼",
  },
  {
    name: "Alex T.",
    gain: 14.52,
    emoji: "🧑‍💼",
  },
  {
    name: "Emma L.",
    gain: 12.34,
    emoji: "👩‍🦰",
  },
  {
    name: "David K.",
    gain: 10.91,
    emoji: "👨‍🦱",
  },
]

export const activityData = [
  {
    userName: "Jack Cuvello",
    userEmoji: "👨‍💼",
    time: "10:32 AM",
    postType: "stock",
    title: "I'm buying TSLA",
    change: -0.54,
    sharesBought: 3,
    orderTotal: 723.16,
    marketCap: "$775.4B",
    revenue: "$24.32B",
  },
  {
    userName: "Emma Lawrence",
    userEmoji: "👩‍💼",
    time: "9:45 AM",
    postType: "stock",
    title: "Just bought more AAPL",
    change: 1.23,
    sharesBought: 5,
    orderTotal: 937.25,
    marketCap: "$2.94T",
    revenue: "$94.84B",
  },
  {
    userName: "Michael Rodriguez",
    userEmoji: "🧑‍💼",
    time: "Yesterday",
    postType: "text",
    content: "The market is looking bullish today! Anyone else seeing gains across their portfolio?",
  },
  {
    userName: "Sarah Johnson",
    userEmoji: "👩‍🦰",
    time: "Yesterday",
    postType: "stock",
    title: "NVDA is on fire! 🔥",
    change: 6.91,
    sharesBought: 2,
    orderTotal: 2091.56,
    marketCap: "$2.58T",
    revenue: "$26.97B",
  },
  {
    userName: "David Kim",
    userEmoji: "👨‍🦱",
    time: "2 days ago",
    postType: "text",
    content: "Anyone have thoughts on the upcoming Fed meeting? How will it affect our positions?",
  },
  {
    userName: "Olivia Parker",
    userEmoji: "👱‍♀️",
    time: "3 days ago",
    postType: "stock",
    title: "Sold my META shares",
    change: -0.53,
    sharesBought: 8,
    orderTotal: 3825.76,
    marketCap: "$1.23T",
    revenue: "$134.90B",
  },
]
