export const leaderboardData = [
  {
    name: "David K.",
    emoji: "👨‍🦰",
    return: 14.3,
    value: 42500,
    trades: 32,
  },
  {
    name: "Emma L.",
    emoji: "👩‍🦱",
    return: 13.8,
    value: 38750,
    trades: 27,
  },
  {
    name: "Jason M.",
    emoji: "👨‍🦲",
    return: 12.5,
    value: 56200,
    trades: 45,
  },
  {
    name: "Sophia N.",
    emoji: "👩",
    return: 11.9,
    value: 31400,
    trades: 19,
  },
  {
    name: "Ryan O.",
    emoji: "🧔",
    return: 10.7,
    value: 47800,
    trades: 38,
  },
  {
    name: "Olivia P.",
    emoji: "👱‍♀️",
    return: 9.8,
    value: 29600,
    trades: 23,
  },
  {
    name: "Thomas Q.",
    emoji: "👨‍🦱",
    return: 8.5,
    value: 52100,
    trades: 41,
  },
  {
    name: "Ava R.",
    emoji: "👩‍🦰",
    return: 7.2,
    value: 34800,
    trades: 29,
  },
  {
    name: "William S.",
    emoji: "👨",
    return: 6.9,
    value: 45300,
    trades: 36,
  },
  {
    name: "Isabella T.",
    emoji: "👩‍🦳",
    return: 5.4,
    value: 28700,
    trades: 21,
  },
  {
    name: "James U.",
    emoji: "🧓",
    return: 4.8,
    value: 39200,
    trades: 31,
  },
  {
    name: "Mia V.",
    emoji: "👵",
    return: 3.6,
    value: 26500,
    trades: 18,
  },
  {
    name: "Benjamin W.",
    emoji: "👴",
    return: 2.9,
    value: 41700,
    trades: 33,
  },
  {
    name: "Charlotte X.",
    emoji: "👧",
    return: 1.7,
    value: 23900,
    trades: 15,
  },
  {
    name: "Daniel Y.",
    emoji: "👦",
    return: 0.8,
    value: 37600,
    trades: 30,
  },
  {
    name: "Amelia Z.",
    emoji: "👩‍🎓",
    return: -1.2,
    value: 22400,
    trades: 14,
  },
  {
    name: "Matthew A.",
    emoji: "👨‍🎓",
    return: -2.5,
    value: 35100,
    trades: 28,
  },
  {
    name: "Harper B.",
    emoji: "👩‍💼",
    return: -3.7,
    value: 21800,
    trades: 13,
  },
]
